name: Release App
on:
  #workflow_dispatch
  release:
    types: [published]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  namefile:
    name: 🚀 Release application
    runs-on: ubuntu-latest
    environment: 
      name: DEV
    steps:
      - name: Start
        run: echo "Starting job"
        
      - name: Checkout source
        uses: actions/checkout@v2
 
      # Update application version in the config.xml file
      - name: Update version
        run: |
          echo "VERSION -> ${{ github.event.release.tag_name }}"
          echo "Something -> ${{ github.event.release.body }} "
      
      # Notify Via Email
      - name: Notify
        run: echo "Hello World"

